AUTH/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$',  login,name='login'),
    url(r'^user/$', user,name='user'),
    url(r'^password/$',password,name='password'),
    url(r'^logout/$', logout,name='logout'),
]

EWP_OMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from AUTH.views import index

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^auth/', include('AUTH.urls',namespace='auth')),
    url(r'^cmdb/', include('CMDB.urls', namespace="cmdb")),
    url(r'^salt/', include('SALT.urls', namespace="salt")),
    url(r'^zabbix/', include('ZABBIX.urls', namespace="zabbix")),
    # url(r'^cobber/', include('cobber.urls', namespace="cobber")),
    url(r'^admin/', include(admin.site.urls)),
]

SALT/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *
from file_local import *
from file_remote import *
from deploy import *
from django.conf import settings

urlpatterns = [
    #基本配置
    url(r'^command/$', command, name='command'),
    url(r'^server/$', server, name='server'),
    url(r'^config/(?P<server_id>[0-9]+)/$', config, name='config'),
    url(r'^config_fun/(?P<server_id>[0-9]+)/$', config_fun, name='config_fun'),
    #客户端管理
    url(r'^minions/(?P<server_id>[0-9]+)/$', minions, name='minions'),
    url(r'^minions_fun/$', minions_fun, name='minions_fun'),
    #命令操作
    url(r'^execute/(?P<server_id>[0-9]+)/$', execute, name='execute'),
    url(r'^execute_fun/(?P<server_id>[0-9]+)/$', execute_fun, name='execute_fun'),
    url(r'^result/$', result, name='result'),
    url(r'^jid_info/$', jid_info, name='jid_info'),
    #本地文件管理
    url(r'^file_local/$', file_local, name='file_local'),
    url(r'^file_create/$', file_create, name='file_create'),
    url(r'^file_rename/$', file_rename, name='file_rename'),
    url(r'^file_write/$', file_write, name='file_write'),
    url(r'^file_delete/$', file_delete, name='file_delete'),
    url(r'^file_upload/$', file_upload, name='file_upload'),
    url(r'^svn/$', svn, name='svn'),
    #远程文件管理
    url(r'^file_remote/(?P<server_id>[0-9]+)/$', file_remote, name='file_remote'),
    url(r'^file_remote_create/$', file_remote_create, name='file_remote_create'),
    url(r'^file_remote_rename/$', file_remote_rename, name='file_remote_rename'),
    url(r'^file_remote_write/$', file_remote_write, name='file_remote_write'),
    url(r'^file_remote_delete/$', file_remote_delete, name='file_remote_delete'),
    #发布管理
    url(r'^deploy/(?P<server_id>[0-9]+)/$', deploy, name='deploy'),
    url(r'^deploy_fun/(?P<server_id>[0-9]+)/$', deploy_fun, name='deploy_fun'),
    url(r'^state/(?P<server_id>[0-9]+)/$', state, name='state'),
    url(r'^state_fun/(?P<server_id>[0-9]+)/$', state_fun, name='state_fun'),
    url(r'^state_history/$', state_history, name='state_history'),
    #文件下载
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    ]

ZABBIX/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^host/$', host, name='host'),
    url(r'^host_create/$', host_create, name='host_create'),
    url(r'^item/$', item, name='item'),
    url(r'^template/$', template, name='template'),
    url(r'^graph/$', graph, name='graph'),
    url(r'^history/$', history, name='history'),
    # url(r'^server/$', server, name='server'),
    # url(r'^config/(?P<server_id>[0-9]+)/$', config, name='config'),
    ]

ZABBIX/models.py
from django.db import models

# Create your models here.

ZABBIX/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import  render,render_to_response,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required  #setting: LOGIN_URL = '/auth/login/'
from django.shortcuts import redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import  PasswordChangeForm
from models import *
from CMDB.models import *
from ZabbixAPI import ZabbixAPI
import json
from django.forms.models import model_to_dict
import re
# from pyzabbix import ZabbixAPI
import ConfigParser
import datetime
import time

@login_required
def host(request):
    try:
        zapi=ZabbixAPI()
        host_list=zapi.HostGet()
        group_list=zapi.HostGroupGet()
        template_list=zapi.TemplateGet()
    except Exception as e:
        error=str(e)
    return render(request, 'ZABBIX/host.html', locals())


@login_required
def host_create(request):
    name=request.GET.get('name','')
    ip=request.GET.get('ip','')
    groupid=request.GET.get('groupid','')
    templateid=request.GET.get('templateid','')

    try:
        zapi=ZabbixAPI()
        hostcreate=zapi.HostCreate(name,ip,groupid,templateid)
        if hostcreate['hostids']:
            result=u"主机%s创建成功，ID为%s."%(name,hostcreate['hostids'])
        else:
            result=u"主机%s创建失败."%(name)
    except Exception as e:
        result=str(e)
    return JsonResponse(result,safe=False)


@login_required
def template(request):
    return render(request, 'ZABBIX/template.html', locals())
@login_required
def item(request):
    cf = ConfigParser.ConfigParser()
    cf.read("EWP_OMS/config.ini")
    itemurl = cf.get("zabbix_server","itemurl")

    hostid=request.GET.get('hostid','')
    try:
        zapi=ZabbixAPI()
        host_list=zapi.HostGet()
        if hostid:
            item_list=zapi.ItemGet(hostid=hostid)
        else:
            item_list=zapi.ItemGet()
        #时间戳转化成日期格式
        for item in item_list:
            item['lastclock']= time.strftime('%Y/%m/%d %H:%M', time.localtime(float(item['lastclock'])))
    except Exception as e:
        error=str(e)
    return render(request, 'ZABBIX/item.html', locals())
@login_required
def graph(request):
    cf = ConfigParser.ConfigParser()
    cf.read("EWP_OMS/config.ini")
    graphurl = cf.get("zabbix_server","graphurl")

    hostid=request.GET.get('hostid','')
    try:
        zapi=ZabbixAPI()
        host_list=zapi.HostGet()
        if hostid:
            graph_list=zapi.GraphGet(hostid=hostid)
        else:
            graph_list=zapi.GraphGet()
    except Exception as e:
        error=str(e)
    return render(request, 'ZABBIX/graph.html', locals())
@login_required
def screen(request):
    return render(request, 'ZABBIX/screen.html', locals())
@login_required
def history(request):
    itemid=request.GET.get('itemid','')
    data_type=request.GET.get('data_type','0')
    print data_type
    try:
        zapi=ZabbixAPI()
        if itemid:
            value=[]
            clock=[]
            item=zapi.ItemGet(itemid=itemid)[0]
            host=zapi.HostGet(hostid=item['hostid'])[0]
            history_list=zapi.History(itemid,int(data_type))
            for history in history_list:
                value.append(float(history['value']))
                clock.append(time.strftime('%Y/%m/%d %H:%M', time.localtime(float(history['clock']))))
            print history_list
    except Exception as e:
        error=str(e)
    return render(request, 'ZABBIX/history.html', locals())

templates/ZABBIX/graph.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% load pagination_tags %}
{% block title %}
    <title>Graph列表</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Graph列表
            <div class="btn-group pull-right">
                <div class="btn-group">
                    <label for="host" class="sr-only"></label>
                    <select class="form-control" id="host">
                        <option value="">选择主机</option>
                        {% for host in host_list %}
                            <option value="{{ host.hostid }}" >{{ host.host }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="btn-group">
                    <label for="graph" class="sr-only"></label>
                    <select class="form-control" id="graph" onchange="GetGraph()">
                        <option value="">选择图像</option>
                        {% for graph in graph_list %}
                            <option value="{{ graph.graphid }}"><span title="{{ graph.name }}">{{ graph.name|truncatechars:40 }}</span></option>
                        {% endfor %}
                    </select>
                </div>
                <div class="btn-group">
                    <label for="period" class="sr-only"></label>
                    <select class="form-control" id="period" onchange="GetGraph()">
                        <option value="3600">选择时间</option>
                        <option value="3600">1小时</option>
                        <option value="7200">2小时</option>
                        <option value="86400">一天</option>
                        <option value="604800">一周</option>
                        <option value="2592000">一个月</option>
                    </select>
                </div>
                <button class="btn btn-default" onclick="GetGraph()" title="刷新"><span class="glyphicon glyphicon-refresh"></span></button>
            </div>
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}

        <hr>
        <div class="row">
{#            <div class="col-xs-3 col-md-3 col-lg-3">#}
{#                {% autopaginate graph_list 15 %}#}
{#                    {% for graph in graph_list %}#}
{#                        <button class="btn btn-primary btn-sm" onclick="GetGraph('{{ graph.graphid }}','{{ graph.name }}','3600')" title="显示图片" >#}
{#                            {{ graph.name }}#}
{#                        </button><br>#}
{#                    {% endfor %}#}
{#                {% paginate %}#}
{#            </div>#}
            <div class="col-xs-12 col-md-12 col-lg-12">
                <img id="img" src="" style="width:100%">
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    <script>
        $(function(){
             $("#host").val("{{ hostid }}");
        });
        $('#host').change(function(){
            var hostid=$(this).val();
            if (!hostid){alert("请选择主机！")}
            else{window.location.href="{% url 'zabbix:graph' %}?hostid="+hostid;}
        });
        function GetGraph(){
            var period=$('#period').val();
            var graphid=$('#graph').val();
            if(!graphid){alert("请选择一个图像对象！")}
            else{$('#img').attr("src","{{ graphurl }}?graphid="+graphid+"&period="+period);}
        }
    </script>
{% endblock %}

templates/ZABBIX/history.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% block title %}
    <title>History</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            History
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}
        <hr>
        <div id="container"></div>
    </div>
{% endblock %}

{% block scripts %}
{#// jQuery#}
{#    <script src="http://cdn.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>#}
{#// Highcharts#}
    <script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
    <script>
    $(function () {
    $('#container').highcharts({                   //图表展示容器，与div的id保持一致
        chart: {
            type: 'area'                         //指定图表的类型，默认是折线图（line）
        },
        title: {
            text: '{{ host.name }}:{{ item.name }}'      //指定图表标题
        },
        xAxis: {
            categories: [{% for c in clock %}{% if  forloop.last %}'{{ c }}'{% else %}'{{ c }}',{% endif %}{% endfor %}]   //指定x轴分组
        },
{#        yAxis: {#}
{#            title: {#}
{#                text: '{{ item.description }}'                  //指定y轴的标题#}
{#            }#}
{#        },#}
        tooltip: {
            shared: true
        },
        legend: {
            enabled: false
        },
        series: [{                                 //指定数据列
            name: '{{ item.key_ }}',                          //数据列名
            data: {{ value }}                        //数据
        }]
    });
});
    </script>
{% endblock %}

templates/ZABBIX/host.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% load pagination_tags %}
{% block title %}
    <title>Zabbix主机</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Zabbix主机列表
{#            <div class="btn-group pull-right">#}
{#                <div class="btn-group " >#}
{#                    <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">#}
{#                        <span class="glyphicon glyphicon-filter"></span>&nbsp;模块&nbsp;<span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="{% url 'salt:command' %}">所有模块</a></li>#}
{#                        {% for module in module_list %}#}
{#                        <li><a href="{% url 'salt:command' %}?module_id={{ module.id }}">{{ module }}</a></li>#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#                </div>#}
{#                <a class="btn btn-info " href="/admin/SALT/module/add/" target="_blank">#}
{#                    <span class="glyphicon glyphicon-plus"></span>&nbsp;模块</a>#}
{#                <a class="btn btn-info " href="/admin/SALT/command/add/" target="_blank">#}
{#                    <span class="glyphicon glyphicon-plus"></span>&nbsp;命令</a>#}
{#                <a class="btn btn-info " href="{% url 'salt:command' %}?active=collect">#}
{#                    <span class="glyphicon glyphicon-cloud-download"></span>&nbsp;采集信息</a>#}
{#            </div>#}
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}
        <div class="row">
            <div class="col-xs-2 col-md-2 col-lg-2">
                <label for="name" class="sr-only"></label>
                <input class="form-control" type="text" id="name" placeholder="输入主机名称">
            </div>
            <div class="col-xs-2 col-md-2 col-lg-2">
                <label  for="ip" class="sr-only"></label>
                <input class="form-control" type="text" id="ip" placeholder="输入主机IP地址">
            </div>
            <div class="col-xs-3 col-md-3 col-lg-3">
                <label for="group" class="sr-only"></label>
                <select class="form-control" id="group">
                    <option value="">选择分组</option>
                    {% for group in group_list %}
                    <option value="{{ group.groupid }}">{{ group.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-xs-3 col-md-3 col-lg-3">
                <label for="template" class="sr-only"></label>
                <select class="form-control" id="template">
                    <option value="">选择模板</option>
                    {% for template in template_list %}
                    <option value="{{ template.templateid }}">{{ template.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-xs-2 col-md-2 col-lg-2">
                <button class="btn btn-default pull-right" type="button" id="create">添加主机</button>
            </div>
        </div>
    <br>
        {% if host_list %}
        {% autopaginate host_list 20 %}
            <div class="table-responsive">
                 <table class="table table-hover table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Host</th>
                            <th>Interfaces</th>
                            <th>Groups</th>
                            <th>Templates</th>
                            <th>Items</th>
                            <th>Triggers</th>
                            <th>Graphs</th>
                            <th>Screens</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    {% for host in host_list %}
                        <tbody>
                            <tr>
                                <td>{{ host.host }}</td>
                                <td>{% for h in host.interfaces  %}
                                    {{ h.ip }}<br>
                                    {% endfor %}</td>
                                <td>{% for h in host.groups  %}
                                    {{ h.name }}<br>
                                    {% endfor %}</td>
{#                                <td>{% for h in host.parentTemplates  %}#}
{#                                    {{ h.name }}<br>#}
{#                                    {% endfor %}</td>#}
                                <td><a href="{% url 'zabbix:template' %}?hostid={{ host.hostid }}">Templates&nbsp;<span class="badge">{{ host.parentTemplates|length }}</span></td>
                                <td><a href="{% url 'zabbix:item' %}?hostid={{ host.hostid }}">Items&nbsp;<span class="badge">{{ host.items|length }}</span></a></td>
                                <td><a href="{% url 'zabbix:item' %}?hostid={{ host.hostid }}">Triggers&nbsp;<span class="badge">{{ host.triggers|length }}</span></a></td>
                                <td><a href="{% url 'zabbix:graph' %}?hostid={{ host.hostid }}">Graphs&nbsp;<span class="badge">{{ host.graphs|length }}</span></a></td>
                                <td><a href="{% url 'zabbix:item' %}?hostid={{ host.hostid }}">Screens&nbsp;<span class="badge">{{ host.screens|length }}</span></a></td>
                                <td>{% if host.status == '0' %}<label class="label label-success">Enable</label>
                                    {% else %}<label class="label label-danger">Disable</label>{% endif %}
                                </td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
            {% paginate %}
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $('#create').click(function(){
            var name=$('#name').val();
            var ip=$('#ip').val();
            var groupid=$('#group').val();
            var templateid=$('#template').val();
            $.getJSON("{% url 'zabbix:host_create' %}",{name:name,ip:ip,groupid:groupid,templateid:templateid},function(result){
                alert(result);
            });
        });
    </script>
{% endblock %}

templates/ZABBIX/item.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% load pagination_tags %}
{% block title %}
    <title>Item列表</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Item列表
            <div class="btn-group pull-right">
                <div id="itemid" class="sr-only"></div>
                <div class="btn-group">
                    <label for="host" class="sr-only"></label>
                    <select class="form-control" id="host">
                        <option value="">选择主机</option>
                        {% for host in host_list %}
                            <option value="{{ host.hostid }}" >{{ host.host }}</option>
                        {% endfor %}
                    </select>
                </div>
{#                <div class="btn-group">#}
{#                    <label for="graph" class="sr-only"></label>#}
{#                    <select class="form-control" id="graph" onchange="GetGraph()">#}
{#                        <option value="">选择图像</option>#}
{#                        {% for graph in graph_list %}#}
{#                            <option value="{{ graph.graphid }}"><span title="{{ graph.name }}">{{ graph.name|truncatechars:40 }}</span></option>#}
{#                        {% endfor %}#}
{#                    </select>#}
{#                </div>#}
                <div class="btn-group">
                    <label for="period" class="sr-only"></label>
                    <select class="form-control" id="period" onchange="GetItem($('#itemid').html())">
                        <option value="3600">选择时间</option>
                        <option value="3600">1小时</option>
                        <option value="7200">2小时</option>
                        <option value="86400">一天</option>
                        <option value="604800">一周</option>
                        <option value="2592000">一个月</option>
                    </select>
                </div>
                <button class="btn btn-default" onclick="GetItem($('#itemid').html())" title="刷新"><span class="glyphicon glyphicon-refresh"></span></button>
            </div>
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}
        <hr>
        <img id="img" src="" style="width:100%">
        {% if item_list %}
        {% autopaginate item_list 20 %}
            <div class="table-responsive">
                 <table class="table table-hover table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>NAME</th>
                            <th>KEY</th>
                            <th>INTERVAL</th>
                            <th>HISTORY</th>
                            <th>TRENDS</th>
                            <th>LASTNS</th>
                            <th>LASTVALUE</th>
                            <th>STATUS</th>
                        </tr>
                    </thead>
                     <tbody>
                     {% for item in item_list %}
                        <tr>
                            <td><a href="#" onclick="GetItem('{{ item.itemid }}')" title="{{ item.description }}">{{ item.name }}</a></td>
                            <td>{{ item.key_ }}</td>
                            <td>{{ item.delay }}sec</td>
                            <td>{{ item.history }}day</td>
                            <td>{{ item.trends }}day</td>
                            <td>{{ item.lastclock }}</td>
                            <td class="text text-danger"><a href="{% url 'zabbix:history' %}?itemid={{ item.itemid }}&datatype={{ item.data_type }}" target="_blank">{{ item.lastvalue }}</a></td>
                            <td>{% if item.status == '0' %}<label class="label label-success">Enable</label>
                                {% else %}<label class="label label-danger">Disable</label>{% endif %}
                            </td>
                        </tr>
                     {% endfor %}
                     </tbody>
                </table>
            </div>
            {% paginate %}
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(function(){
             $("#host").val("{{ hostid }}");
        });
        $('#host').change(function(){
            var hostid=$(this).val();
            if (!hostid){alert("请选择主机！")}
            else{window.location.href="{% url 'zabbix:item' %}?hostid="+hostid;}
        });
        function GetItem(itemid){
            var period=$('#period').val();
{#            var itemid=$('#item').val();#}
            $('#itemid').html(itemid);
            if(!itemid){alert("请选择一个监控对象！")}
            else{$('#img').attr("src","{{ itemurl }}?itemids="+itemid+"&period="+period);}
        }
    </script>
{% endblock %}

templates/ZABBIX/screen.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% block title %}
    <title>Zabbix主机</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Zabbix主机列表
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}
    
{% endblock %}

templates/ZABBIX/template.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% block title %}
    <title>Zabbix主机</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Zabbix主机列表
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}

{% endblock %}