AUTH/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$',  login,name='login'),
    url(r'^user/$', user,name='user'),
    url(r'^password/$',password,name='password'),
    url(r'^logout/$', logout,name='logout'),
]

CMDB/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^idc/$', idc, name='idc'),
    url(r'^server/$', server, name='server'),
    url(r'^system/$', system, name='system'),
    url(r'^host/$', host, name='host'),
    url(r'^detail/(?P<ip>[0-9.]+)/$', detail, name='detail'),
    url(r'^network/$', network, name='network'),
    url(r'^initialize/(?P<host_id>\d+)/$', initialize, name='initialize'),
    url(r'^collect/(?P<host_id>\d+)/$', collect, name='collect'),
    # url(r'^account/(?P<device>.+)/(?P<id>[0-9].+)/$', account, name='account'),

]

EWP_OMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from AUTH.views import index

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^auth/', include('AUTH.urls',namespace='auth')),
    url(r'^cmdb/', include('CMDB.urls', namespace="cmdb")),
    url(r'^salt/', include('SALT.urls', namespace="salt")),
    url(r'^zabbix/', include('ZABBIX.urls', namespace="zabbix")),
    # url(r'^cobber/', include('cobber.urls', namespace="cobber")),
    url(r'^admin/', include(admin.site.urls)),
]

CMDB/models.py
#coding: utf-8
from django.db import models

# Create your models here.
class IDC(models.Model):
    IDCType = (
        ('DX', u'电信'),
        ('LT', u'联通'),
        ('YD', u'移动'),
        ('ZJ', u'自建'),
    )
    name = models.CharField(unique=True,max_length=50, verbose_name=u'机房名称')
    type = models.CharField(choices=IDCType,max_length=20, verbose_name=u'机房类型',default='DX')
    address = models.CharField(blank=True,max_length=100, verbose_name=u'机房地址')
    contact = models.CharField(blank=True,max_length=100, verbose_name=u'联系方式')
    start_date = models.DateField(null=True,blank=True,verbose_name=u'租赁日期')
    end_date = models.DateField(null=True,blank=True, verbose_name=u'到期日期')
    cost = models.CharField(blank=True, max_length=20,verbose_name=u'租赁费用')
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'机房'
        verbose_name_plural = u'机房列表'

class SystemType(models.Model):
    name = models.CharField(max_length=30,unique=True,verbose_name=u'系统类型')
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'系统类型'
        verbose_name_plural = u'系统类型列表'

class HostGroup(models.Model):
    name = models.CharField(max_length=30,unique=True)
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'主机组'
        verbose_name_plural = u'主机组列表'

class HostDetail(models.Model):
    ip  = models.GenericIPAddressField(unique=True,verbose_name=u'IP')
    tgt_id = models.CharField(max_length=50,blank=True,verbose_name=u'目标ID')
    fqdn  = models.CharField(max_length=50,blank=True,verbose_name=u'计算机全称')
    domain  = models.CharField(max_length=50,blank=True,verbose_name=u'域名')
    hwaddr_interfaces  = models.CharField(max_length=150,blank=True,verbose_name=u'MAC地址')
    cpu_model  = models.CharField(max_length=50,blank=True,verbose_name=u'CPU型号')
    kernel  = models.CharField(max_length=50,blank=True,verbose_name=u'内核')
    os  = models.CharField(max_length=50,blank=True,verbose_name=u'操作系统')
    osarch  = models.CharField(max_length=50,blank=True,verbose_name=u'系统架构')
    osrelease  = models.CharField(max_length=50,blank=True,verbose_name=u'系统版本')
    productname  = models.CharField(max_length=50,blank=True,verbose_name=u'产品型号')
    serialnumber  = models.CharField(max_length=50,blank=True,verbose_name=u'序列号')
    server_id  = models.CharField(max_length=50,blank=True,verbose_name=u'服务ID')
    virtual  = models.CharField(max_length=50,blank=True,verbose_name=u'虚拟环境')
    salt_status  = models.BooleanField(default=False,verbose_name=u'Salt状态')
    zbx_status  = models.BooleanField(default=False,verbose_name=u'Zabbix状态')
    def __unicode__(self):
        return self.ip
    class Meta:
        verbose_name = u'主机详细信息'
        verbose_name_plural = u'主机详细信息列表'

class Server(models.Model):
    ip = models.OneToOneField('HostDetail',verbose_name=u'IP地址')
    name = models.CharField(max_length=50,blank=True, verbose_name=u'服务器名称')
    idc = models.ForeignKey(IDC,verbose_name=u'所属机房')
    location = models.CharField(max_length=30,blank=True,verbose_name=u'机架位置')
    start_date = models.DateField(verbose_name=u'启用日期')
    status = models.BooleanField(default=True ,verbose_name=u'使用状态')
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'服务器'
        verbose_name_plural = u'服务器列表'

class Host(models.Model):
    ip = models.OneToOneField(HostDetail,verbose_name=u'IP地址')
    server = models.ForeignKey(Server,verbose_name=u'所属服务器')
    system_type = models.ForeignKey(SystemType,verbose_name=u'操作系统类型')
    group = models.ManyToManyField('HostGroup',blank=True ,verbose_name=u'所属主机组')
    start_date = models.DateField(verbose_name=u'启用日期')
    status = models.BooleanField(default=True ,verbose_name=u'使用状态')
    username = models.CharField(max_length=20,blank=True,verbose_name=u'用户名')
    password = models.CharField(max_length=50,blank=True,verbose_name=u'密码')
    def __unicode__(self):
        return self.ip.ip
    class Meta:
        verbose_name = u'主机'
        verbose_name_plural = u'主机列表'

class Network(models.Model):
    name = models.CharField(max_length=30, verbose_name=u'名称')
    brand = models.CharField(max_length=30,blank=True, verbose_name=u'品牌')
    model = models.CharField(max_length=30,blank=True, verbose_name=u'型号')
    ip_out = models.GenericIPAddressField(unique=True,null=True,blank=True,verbose_name=u'外网IP地址')
    ip_in = models.GenericIPAddressField(unique=True,null=True,blank=True, verbose_name=u'内网IP地址')
    info = models.CharField(max_length=100,blank=True, verbose_name=u'说明')
    url = models.URLField(max_length=100, blank=True,verbose_name=u'访问地址')
    username = models.CharField(max_length=20,blank=True,verbose_name=u'用户名')
    password = models.CharField(max_length=50,blank=True,verbose_name=u'密码')
    idc = models.ForeignKey(IDC,verbose_name=u'所属机房')
    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'网络设备'
        verbose_name_plural = u'网络设备列表'

CMDB/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import  render,render_to_response,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required  #setting: LOGIN_URL = '/auth/login/'
from django.shortcuts import redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import  PasswordChangeForm
from models import *
from SALT.SaltAPI import SaltAPI
from SALT.models import SaltServer

#机房列表
@login_required
def idc(request):
    idc_list= IDC.objects.order_by('pk')
    count = {}  #统计机房中有多少台主机（不含物理主机）
    for idc in idc_list:
        num=0
        for server in idc.server_set.all():
            num+=server.host_set.count()
        count[int(idc.id)]=num
    # print count
    return render(request, 'CMDB/idc.html', locals())
#操作系统列表
@login_required
def system(request):
    system_list= SystemType.objects.order_by('name')
    return render(request, 'CMDB/system.html', locals())
# 服务器列表
@login_required
def server(request):
    system_id = request.GET.get('system_id')
    idc_id = request.GET.get('idc_id')
    system_list = SystemType.objects.order_by('name')
    idc_list = IDC.objects.order_by('name')
    server_list = Server.objects.order_by('ip')
    if system_id:
        if idc_id:
            server_list = server_list.filter(ip__host__systype=system_id,idc=idc_id)
        else:
            server_list = server_list.filter(ip__host__systype=system_id)
    elif idc_id:
        server_list = server_list.filter(idc=idc_id)
    else:
        server_list = server_list
    return render(request, 'CMDB/server.html', locals())
#主机列表
@login_required
def host(request):
    system_id = request.GET.get('system_id')
    server_id = request.GET.get('server_id')
    idc_id=request.GET.get('idc_id')
    hostname=request.POST.get('hostname')
    host_list=Host.objects.order_by('ip')
    system_list = SystemType.objects.order_by('name')
    server_list = Server.objects.order_by('name')
    idc_list = IDC.objects.order_by('name')
    #根据系统、机房、服务器过滤
    if system_id:
        if server_id:
            host_list = host_list.filter(system_type=system_id,server=server_id)
        elif idc_id:
            servers=server_list.filter(idc=idc_id)
            host_list = host_list.filter(system_type=system_id,server__in=servers)
        else:
            host_list = host_list.filter(system_type=system_id)
    elif server_id:
        host_list = host_list.filter(server=server_id)
    elif idc_id:
        servers=server_list.filter(idc=idc_id)
        host_list = host_list.filter(server__in=servers)
    else:
        host_list= host_list.order_by('ip')
    #根据主机名搜索，不区分大小写的匹配
    if hostname:
        host_list =host_list.filter(ip__tgt_id__icontains=hostname)
    else:
        host_list= host_list
    return render(request, 'CMDB/host.html', locals())



#主机详细信息
@login_required
def detail(request, ip):
    host_detail = HostDetail.objects.get(ip=ip)
    return render(request, 'CMDB/detail.html', {'host_detail': host_detail})
#网络设备列表
@login_required
def network(request):
    idc_id = request.GET.get('idc_id')
    if idc_id:
        net_list = Network.objects.filter(idc=idc_id).order_by('name')
    else:
        net_list = Network.objects.order_by('name')
    idc_list = IDC.objects.order_by('name')
    return render(request,'CMDB/network.html',locals())

def initialize(request,host_id):
    #vi /etc/salt/roster
    #10.188.1.43:
    #  host: 10.188.1.43
    #  user: root
    #  passwd: password
    host=HostDetail.objects.get(id=host_id)
    idc = Host.objects.get(ip=host_id).server.idc
    salt_server = SaltServer.objects.get(ip__server__idc=idc)
    sapi = SaltAPI(url=salt_server.url,username=salt_server.username,password=salt_server.password)

    result = sapi.SaltCmd(client='ssh',tgt=host.ip,fun='state.sls',arg='minions.install')
    # 服务端shell执行结果：
    # {u'return': [{u'minion03': {u'fun_args': [], u'jid': u'20160418114256060122', u'return': True, u'retcode': 0, u'fun': u'test.ping', u'id': u'minion03'}}]}
    # 本案返回结果：
    #{u'return': [{u'10.188.1.43': {u'fun_args': [u'/tmp/.root_062b80_salt/salt_state.tgz', u'test=None', u'pkg_sum=9a6345be067f85bfd9cb53cd881e69cb', u'hash_type=md5'], u'jid': u'20160427112651029260', u'return': {u'file_|-epel_repo_|-/etc/yum.repos.d/epel.repo_|-managed': {u'comment': u'File /etc/yum.repos.d/epel.repo is in the correct state', u'name': u'/etc/yum.repos.d/epel.repo', u'start_time': u'11:26:51.094575', u'result': True, u'duration': 22.386, u'__run_num__': 0, u'changes': {}}, u'service_|-salt_service_|-salt-minion_|-running': {u'comment': u'The service salt-minion is already running', u'name': u'salt-minion', u'start_time': u'11:26:52.274941', u'result': True, u'duration': 98.74, u'__run_num__': 3, u'changes': {}}, u'pkg_|-salt_pkg_|-salt-minion_|-installed': {u'comment': u'Package salt-minion is already installed', u'name': u'salt-minion', u'start_time': u'11:26:51.738705', u'result': True, u'duration': 521.291, u'__run_num__': 1, u'changes': {}}, u'file_|-salt_conf_|-/etc/salt/minion_|-managed': {u'comment': u'File /etc/salt/minion is in the correct state', u'name': u'/etc/salt/minion', u'start_time': u'11:26:52.260834', u'result': True, u'duration': 12.585, u'__run_num__': 2, u'changes': {}}}, u'retcode': 0, u'fun': u'state.pkg', u'id': u'10.188.1.43', u'out': u'highstate'}}]}
#     {
#     u'return': [
#         {
#             u'10.188.1.43': {
#                 u'fun_args': [
#                     u'/tmp/.root_062b80_salt/salt_state.tgz',
#                     u'test=None',
#                     u'pkg_sum=9a6345be067f85bfd9cb53cd881e69cb',
#                     u'hash_type=md5'
#                 ],
#                 u'jid': u'20160427112651029260',
#                 u'return': {
#                     u'file_|-epel_repo_|-/etc/yum.repos.d/epel.repo_|-managed': {
#                         u'comment': u'File/etc/yum.repos.d/epel.repoisinthecorrectstate',
#                         u'name': u'/etc/yum.repos.d/epel.repo',
#                         u'start_time': u'11: 26: 51.094575',
#                         u'result': True,
#                         u'duration': 22.386,
#                         u'__run_num__': 0,
#                         u'changes': {
#
#                         }
#                     },
#                     u'service_|-salt_service_|-salt-minion_|-running': {
#                         u'comment': u'Theservicesalt-minionisalreadyrunning',
#                         u'name': u'salt-minion',
#                         u'start_time': u'11: 26: 52.274941',
#                         u'result': True,
#                         u'duration': 98.74,
#                         u'__run_num__': 3,
#                         u'changes': {
#
#                         }
#                     },
#                     u'pkg_|-salt_pkg_|-salt-minion_|-installed': {
#                         u'comment': u'Packagesalt-minionisalreadyinstalled',
#                         u'name': u'salt-minion',
#                         u'start_time': u'11: 26: 51.738705',
#                         u'result': True,
#                         u'duration': 521.291,
#                         u'__run_num__': 1,
#                         u'changes': {
#
#                         }
#                     },
#                     u'file_|-salt_conf_|-/etc/salt/minion_|-managed': {
#                         u'comment': u'File/etc/salt/minionisinthecorrectstate',
#                         u'name': u'/etc/salt/minion',
#                         u'start_time': u'11: 26: 52.260834',
#                         u'result': True,
#                         u'duration': 12.585,
#                         u'__run_num__': 2,
#                         u'changes': {
#
#                         }
#                     }
#                 },
#                 u'retcode': 0,
#                 u'fun': u'state.pkg',
#                 u'id': u'10.188.1.43',
#                 u'out': u'highstate'
#             }
#         }
#     ]
# }
    # jid = result['return'][0][host.ip]['jid']
    print result
    return HttpResponse(result)


#http://www.jb51.net/article/80289.htm
def collect(request,host_id):
    host=HostDetail.objects.get(id=host_id)
    idc = Host.objects.get(ip=host_id).server.idc
    salt_server = SaltServer.objects.get(ip__server__idc=idc)
    sapi = SaltAPI(url=salt_server.url,username=salt_server.username,password=salt_server.password)

    result = sapi.SaltMinions(host.tgt_id)
    grains = result['return'][0].values()[0]
    host.fqdn=grains['fqdn']
    host.domain=grains['domain']
    host.hwaddr_interfaces=grains['hwaddr_interfaces']
    host.cpu_model=grains['cpu_model']
    host.kernel=grains['kernel']
    host.os=grains['os']
    # ipv4 = str(grains[i]["ipv4"]).replace(", '127.0.0.1'","")
    # host.osarch=grains['osarch']
    host.osrelease=grains['osrelease']
    # host.productname=grains['productname']
    # host.serialnumber=grains['serialnumber']
    host.server_id=grains['server_id']
    host.save()
    #CPU核数num_cpus
#硬盘信息disk.usage disk_data = data_vol / 1048576
    return HttpResponseRedirect(reverse('cmdb:host'))


# #保存设备的登陆账号
# def account(request,device,id):
#
#     if request.method == 'POST':
#         if device == 'network':
#             obj=Network.objects.get(pk=id)
#             obj.username=request.POST.get('username')
#             obj.password=encrypt(request.POST.get('password'),SECRET_KEY)
#             obj.save()
#             return HttpResponseRedirect(reverse('cmdb:network'))
#         elif device == 'machine':
#             pass
#         elif device == 'host':
#             pass
#     return render(request,'CMDB/account.html')

templates/CMDB/account.html
<div class="modal-header text-center">
    <h4>设置“{{ device }}”的登陆账号
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </h4>
</div>
<div class="modal-body">
    <form action='/cmdb/account' method='post'>
        {% csrf_token %}
        <label for="username">用户名:</label>
        <input class="form-control" type="text" name="username" value="" id="username" placeholder="username" required><br>
        <label for="password">密码:</label>
        <input class="form-control" type="password" name="password" value="" id="password" placeholder="password" required><br>
        <div class="btn-group-justified" role="group">
            <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default">保 存</button>
            </div>
        </div>
    </form>
<script type="text/javascript">document.getElementById("username").focus();</script>
</div>
<div class="modal-footer">
    <div class="btn-group pull-right">
        <a class="btn btn-info" href="#">提交</a>
        <a class="btn btn-info" data-dismiss="modal">关闭</a>
    </div>
</div>

templates/CMDB/detail.html
        <div class="modal-header text-center">
            <h4>主机 {{ host_detail.ip }} 的详细信息
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </h4>
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal" contenteditable="true">
                <dt>IP地址：</dt><dd>{{ host_detail.ip }}</dd>
                <dt>计算机全称：</dt><dd>{{ host_detail.fqdn }}</dd>
                <dt>域名：</dt><dd>{{ host_detail.domain }}</dd>
                <dt>MAC地址：</dt><dd>{{ host_detail.hwaddr_interfaces }}</dd>
                <dt>CPU型号：</dt><dd>{{ host_detail.cpu_model }}</dd>
                <dt>内核：</dt><dd>{{ host_detail.kernel }}</dd>
                <dt>系统名称：</dt><dd>{{ host_detail.os }}</dd>
                <dt>系统架构：</dt><dd>{{ host_detail.osarch }}</dd>
                <dt>系统版本：</dt><dd>{{ host_detail.osrelease }}</dd>
{#                <dt>产品名称：</dt><dd>{{ host_detail.productname }}</dd>#}
{#                <dt>序列号：</dt><dd>{{ host_detail.serialnumber }}</dd>#}
                <dt>服务ID：</dt><dd>{{ host_detail.server_id }}</dd>
            </dl>
        </div>
        <div class="modal-footer">
            <div class="btn-group pull-right">
                <a class="btn btn-info" href="{% if not host_detail.salt_status %}/cmdb/initialize/{{ host_detail.id }}/{% else %}javascript:void(0);{% endif %}" {% if host_detail.salt_status %}disabled{% endif %}>初始化安装</a>
                <a class="btn btn-info" href="/cmdb/collect/{{ host_detail.id }}/">数据采集</a>
                <a class="btn btn-info" data-dismiss="modal">关闭</a>
            </div>
        </div>

templates/CMDB/idc.html
{% extends "AUTH/navbar.html" %}
{% block title %}<title>OMS｜资产管理｜数据中心资产</title>{% endblock %}
{% block content %}
    <div class="container">
        <h2>数据中心资产管理
            <span class="pull-right">
                <a class="btn btn-info" href="/admin/CMDB/idc/add/" target="_blank">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;数据中心</a>
            </span>
        </h2>
       <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                    <tr>
                        <th>机房名称</th>
                        <th>机房类型</th>
                        <th>机房地址</th>
                        <th>联系方式</th>
                        <th>租赁日期</th>
                        <th>到期日期</th>
                        <th>租赁费用</th>
                        <th>服务器</th>
                        <th>主机</th>
                        <th>网络</th>
                        <th>操作</th>
                    </tr>
                </thead>
                {% for idc in idc_list %}
                    <tbody>
                        <tr>
                            <td>{{ idc.name }}</td>
                            <td>{{ idc.get_type_display }}</td>
                            <td>{{ idc.address }}</td>
                            <td>{{ idc.contact }}</td>
                            <td>{{ idc.start_date }}</td>
                            <td>{{ idc.end_date }}</td>
                            <td>{{ idc.cost }}</td>
                            <td><a href="{% url 'cmdb:server' %}?idc_id={{ idc.id }}">
                                {{ idc.server_set.count }}台</a></td>
                            <td>
                                <a href="{% url 'cmdb:host' %}?idc_id={{ idc.id }}">
                                    {% for k,v in count.items %}
                                        {% if k == idc.id %}
                                            {{ v }}台
                                        {% endif %}
                                    {% endfor %}
                                    </a>
                            </td>
                            <td><a href="{% url 'cmdb:network' %}?idc_id={{ idc.id }}">
                                {{ idc.network_set.count }}台</a></td>
                            <td>
                                <a class="btn btn-info btn-xs" href="/admin/CMDB/idc/{{ idc.id }}/" target="_blank">
                                    <span class="glyphicon glyphicon-edit"></span>&nbsp;修&nbsp;改
                                </a>
                            </td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/CMDB/server.html
{% extends "AUTH/navbar.html" %}
{% load pagination_tags %}
{% block title %}<title>服务器</title>{% endblock %}
{% block content %}
    <div class="container">
        <h2>服务器资产管理
            <div class="btn-group pull-right">

                <div class="btn-group dropdown">
                    <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-filter"></span>&nbsp;系统&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'cmdb:server' %}{% if idc_id %}?idc_id={{ idc_id }}{% endif %}">所有系统</a></li>
                        {% for system in system_list %}
                        <li><a href="{% url 'cmdb:server' %}?system_id={{ system.id }}{% if idc_id %}&idc_id={{ idc_id }}{% endif %}">{{ system.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="btn-group dropdown">
                    <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-filter"></span>&nbsp;机房&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'cmdb:server' %}{% if system_id %}?system_id={{ system_id }}{% endif %}">所有机房</a></li>
                        {% for idc in idc_list %}
                        <li><a href="{% url 'cmdb:server' %}?idc_id={{ idc.id }}{% if system_id %}&system_id={{ system_id }}{% endif %}">{{ idc.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

                <a class="btn btn-info" href="/admin/CMDB/server/add/" target="_blank"><span class="glyphicon glyphicon-plus"></span>&nbsp;服务器</a>
            </div>
        </h2>
        {% autopaginate server_list 8 %}
        <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                    <tr>
                        <th>IP地址</th>
                        <th>服务器名称</th>
                        <th>系统类型</th>
                        <th>所属机房</th>
                        <th>机架位置</th>
                        <th>上架日期</th>
                        <th>使用状态</th>
                        <th>主机</th>
                        <th>操作</th>
                    </tr>
                </thead>
                {% for server in server_list %}
                    <tbody>
                        <tr>
                            <td><a href="{% url 'cmdb:detail' server.ip %}" title="详细信息"  data-toggle="modal" data-target="#server_modal">
                                {{ server.ip }}</a></td>
                            <td>{{ server.name }}</td>
                            <td>{{ server.ip.host.system_type.name }}</td>
                            <td>{{ server.idc }}</td>
                            <td>{{ server.location }}</td>
                            <td>{{ server.start_date }}</td>
                            <td>{{ server.status }}</td>
                            <td><a href="{% url 'cmdb:host' %}?server_id={{ server.id }}">
                                {{ server.host_set.count }}台</a></td>
                            <td>
                                <a class="btn btn-info btn-xs" href="/admin/CMDB/server/{{ server.id }}/" target="_blank">
                                    <span class="glyphicon glyphicon-edit"></span>&nbsp;修&nbsp;改
                                </a>
                            </td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
        {% paginate %}
    </div>
    <div class="modal fade" id="server_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog">
        <div class="modal-content"></div>
      </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
         $('#server_modal').on('hidden.bs.modal', function () {
            $(this).removeData("bs.modal")
              ;})
    </script>
{% endblock %}

templates/CMDB/system.html
{% extends "AUTH/navbar.html" %}
{% block title %}<title>操作系统</title>{% endblock %}
{% block content %}
    <div class="container">
        <h2>操作系统管理
            <div class="btn-group pull-right">
                <a class="btn btn-info" href="/admin/CMDB/systemtype/add/" target="_blank">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;系统类型</a>
            </div>
        </h2>
       <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                    <tr>
{#                        <th>系统名称</th>#}
                        <th>系统类型</th>
{#                        <th>服务器</th>#}
                        <th>主机</th>
                        <th>操作</th>
                    </tr>
                </thead>
                {% for system in system_list %}
                    <tbody>
                        <tr>
                            <td>{{ system.name }}</td>
{#                            <td>{{ system.get_type_display }}</td>#}
{#                            <td><a href="{% url 'cmdb:server' %}?system_id={{ system.id }}">#}
{#                                {{ system.host_set.ip.server_set.count }}台</a></td>#}
                            <td><a href="{% url 'cmdb:host' %}?system_id={{ system.id }}">
                                {{ system.host_set.count }}台</a></td>
                            <td>
                                <a class="btn btn-info btn-xs" href="/admin/CMDB/system/{{ system.id }}/" target="_blank">
                                    <span class="glyphicon glyphicon-edit"></span> 修 改
                                </a>
                            </td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}