AUTH/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$',  login,name='login'),
    url(r'^user/$', user,name='user'),
    url(r'^password/$',password,name='password'),
    url(r'^logout/$', logout,name='logout'),
]

EWP_OMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from AUTH.views import index

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^auth/', include('AUTH.urls',namespace='auth')),
    url(r'^cmdb/', include('CMDB.urls', namespace="cmdb")),
    url(r'^salt/', include('SALT.urls', namespace="salt")),
    url(r'^zabbix/', include('ZABBIX.urls', namespace="zabbix")),
    # url(r'^cobber/', include('cobber.urls', namespace="cobber")),
    url(r'^admin/', include(admin.site.urls)),
]

SALT/urls.py
#encoding:utf-8
from django.conf.urls import url
from views import *
from file_local import *
from file_remote import *
from deploy import *
from django.conf import settings

urlpatterns = [
    #基本配置
    url(r'^command/$', command, name='command'),
    url(r'^server/$', server, name='server'),
    url(r'^config/(?P<server_id>[0-9]+)/$', config, name='config'),
    url(r'^config_fun/(?P<server_id>[0-9]+)/$', config_fun, name='config_fun'),
    #客户端管理
    url(r'^minions/(?P<server_id>[0-9]+)/$', minions, name='minions'),
    url(r'^minions_fun/$', minions_fun, name='minions_fun'),
    #命令操作
    url(r'^execute/(?P<server_id>[0-9]+)/$', execute, name='execute'),
    url(r'^execute_fun/(?P<server_id>[0-9]+)/$', execute_fun, name='execute_fun'),
    url(r'^result/$', result, name='result'),
    url(r'^jid_info/$', jid_info, name='jid_info'),
    #本地文件管理
    url(r'^file_local/$', file_local, name='file_local'),
    url(r'^file_create/$', file_create, name='file_create'),
    url(r'^file_rename/$', file_rename, name='file_rename'),
    url(r'^file_write/$', file_write, name='file_write'),
    url(r'^file_delete/$', file_delete, name='file_delete'),
    url(r'^file_upload/$', file_upload, name='file_upload'),
    url(r'^svn/$', svn, name='svn'),
    #远程文件管理
    url(r'^file_remote/(?P<server_id>[0-9]+)/$', file_remote, name='file_remote'),
    url(r'^file_remote_create/$', file_remote_create, name='file_remote_create'),
    url(r'^file_remote_rename/$', file_remote_rename, name='file_remote_rename'),
    url(r'^file_remote_write/$', file_remote_write, name='file_remote_write'),
    url(r'^file_remote_delete/$', file_remote_delete, name='file_remote_delete'),
    #发布管理
    url(r'^deploy/(?P<server_id>[0-9]+)/$', deploy, name='deploy'),
    url(r'^deploy_fun/(?P<server_id>[0-9]+)/$', deploy_fun, name='deploy_fun'),
    url(r'^state/(?P<server_id>[0-9]+)/$', state, name='state'),
    url(r'^state_fun/(?P<server_id>[0-9]+)/$', state_fun, name='state_fun'),
    url(r'^state_history/$', state_history, name='state_history'),
    #文件下载
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    ]

SALT/models.py
#coding: utf-8
from django.db import models
from CMDB.models import IDC,Host
# Create your models here.
class SaltServer(models.Model):
    Role = (
    ('Master', 'Master'),
    ('Backend', 'Backend'),
    )
    idc = models.ForeignKey(IDC,verbose_name=u'所属机房')
    url = models.URLField(max_length=100,verbose_name=u'URL地址')
    username = models.CharField(max_length=50, verbose_name=u'用户名')
    password = models.CharField(max_length=50,verbose_name=u'密码')
    role = models.CharField(choices=Role,max_length=20,default='Master',verbose_name=u'角色')
    def __unicode__(self):
        return u"%s - %s - %s" %(self.idc,self.url,self.role)
    class Meta:
        verbose_name = u'Salt服务器'
        verbose_name_plural = u'Salt服务器列表'

#https://docs.saltstack.com/en/latest/ref/modules/all/index.html
class Module(models.Model):
    client = models.CharField(max_length=20,default='execution',verbose_name=u'Salt模块类型')
    name = models.CharField(max_length=20,verbose_name=u'Salt模块名称')
    def __unicode__(self):
        return "%s - %s "% (self.client,self.name)
    class Meta:
        verbose_name = u'Salt模块'
        verbose_name_plural = u'Salt模块列表'
        unique_together = ("client", "name")

class Command(models.Model):
    cmd = models.CharField(max_length=100,verbose_name=u'Salt命令')
    doc = models.TextField(max_length=1000,blank=True,verbose_name=u'帮助文档')
    module = models.ForeignKey(Module,verbose_name=u'所属模块')
    def __unicode__(self):
        return  u"%s - %s"%(self.module,self.cmd)
    class Meta:
        verbose_name = u'Salt命令'
        verbose_name_plural = u'Salt命令列表'
        unique_together = ("module", "cmd")

class Result(models.Model):
    #命令
    client = models.CharField(max_length=20,blank=True,verbose_name=u'执行方式')
    fun = models.CharField(max_length=50,verbose_name=u'命令')
    arg = models.CharField(max_length=255,blank=True,verbose_name=u'参数')
    tgt_type =  models.CharField(max_length=20,verbose_name=u'目标类型')
    #返回
    jid = models.CharField(blank=True,max_length=50,verbose_name=u'任务号')
    minions = models.CharField(max_length=500,blank=True,verbose_name=u'目标主机')
    result = models.TextField(blank=True,verbose_name=u'返回结果')
    #其他信息
    server = models.ForeignKey(SaltServer,verbose_name=u'所属Salt服务器')
    user = models.CharField(max_length=50,verbose_name=u'操作用户')
    datetime =models.DateTimeField(auto_now_add=True,verbose_name=u'执行时间')
    def __unicode__(self):
        return self.jid
    class Meta:
        verbose_name = u'命令返回结果'
        verbose_name_plural = u'命令返回结果'

class SvnProject(models.Model):
    name = models.CharField(max_length=50,blank=True,verbose_name=u'项目名称')
    salt_server = models.ForeignKey(SaltServer,verbose_name=u'所属Salt服务器')
    host = models.CharField(max_length=50,verbose_name=u'项目主机')
    path = models.CharField(max_length=200,verbose_name=u'项目根路径')
    target = models.CharField(max_length=50,verbose_name=u'项目目录')
    url = models.CharField(max_length=200,verbose_name=u'SVN地址')
    username = models.CharField(max_length=40,verbose_name=u'SVN账号')
    password = models.CharField(max_length=40,blank=True,verbose_name=u'SVN密码')
    status = models.CharField(max_length=40,default=u'新建',verbose_name=u'状态')
    create_date=models.DateTimeField(auto_now_add=True,verbose_name=u'创建时间')
    info = models.TextField(max_length=500,blank=True,verbose_name=u'信息')
    def __unicode__(self):
        return u"%s: %s - %s/%s"%(self.name,self.host,self.path,self.target)
    class Meta:
        verbose_name = u'SVN项目'
        verbose_name_plural = u'SVN项目列表'
        unique_together = ("host", "path", "target")


class Minions(models.Model):
    Status = (
    ('Unknown', 'Unknown'),
    ('Accepted', 'Accepted'),
    ('Denied', 'Denied'),
    ('Unaccepted', 'Unaccepted'),
    ('Rejected', 'Rejected'),
    )
    minion = models.CharField(max_length=50,verbose_name=u'客户端')
    salt_server = models.ForeignKey(SaltServer,verbose_name=u'所属Salt服务器')
    grains = models.TextField(max_length=500,blank=True,verbose_name=u'Grains信息')
    pillar = models.TextField(max_length=500,blank=True,verbose_name=u'Pillar信息')
    status = models.CharField(choices=Status,max_length=20,default='Unknown',verbose_name=u'在线状态')
    # create_date=models.DateTimeField(auto_now_add=True,verbose_name=u'创建时间')
    def __unicode__(self):
        return self.minion
    class Meta:
        verbose_name = u'Salt客户端'
        verbose_name_plural = u'Salt客户端列表'
        unique_together = ("minion", "salt_server")


class State(models.Model):
    #命令
    client = models.CharField(max_length=20,blank=True,verbose_name=u'执行方式')
    fun = models.CharField(max_length=50,verbose_name=u'命令')
    arg = models.CharField(max_length=255,blank=True,verbose_name=u'参数')
    tgt_type =  models.CharField(max_length=20,verbose_name=u'目标类型')
    #返回
    jid = models.CharField(blank=True,max_length=50,verbose_name=u'任务号')
    minions = models.CharField(max_length=500,blank=True,verbose_name=u'目标主机')
    result = models.TextField(blank=True,verbose_name=u'返回结果')
    #其他信息
    server = models.ForeignKey(SaltServer,verbose_name=u'所属Salt服务器')
    user = models.CharField(max_length=50,verbose_name=u'操作用户')
    datetime =models.DateTimeField(auto_now_add=True,verbose_name=u'执行时间')
    def __unicode__(self):
        return self.datetime
    class Meta:
        verbose_name = u'部署结果'
        verbose_name_plural = u'部署结果'

templates/SALT/config.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% block title %}
    <title>SaltMaster配置</title>
    <style>
        textarea {
            white-space: pre;
            font-family: Courier, monospace;
            width:100%;
            height:540px;
            background-color: black;
            color: #ffffff;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            SaltMaster配置
            <small class="text-danger">{{ salt_server.idc.name }} -- {{ salt_server.url }} -- {{ salt_server.role }}</small>
            <label for="server" disabled="disabled"></label>
            <div class="btn-group pull-right dropdown">
                <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    &nbsp;SaltServer&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    {% for s in server_list %}
                        <li><a href="{% url 'salt:config' s.id%}">{{ s.idc.name }} -- {{ s.url }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}

        <div class="row">
            <div class="col-xs-4 col-md-4">
                <div class="form-group">
                    <label for="env">环境列表</label>
                    <select class="form-control" size="6" id="env">
                        {% for env in envs %}
                        <option value="{{ env }}">{{ env }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="file">文件列表</label>
                    <select class="form-control" size="18" id="file">
                    </select>
                </div>
                <button type="button" id="write" class="btn btn-info btn-lg btn-block">Write</button>
            </div>
            <div class="col-xs-8 col-md-8">
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <label for="content">模块文件<code id="name"></code>的内容</label>
                        <div class="form-group">
                            <textarea id="content"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>



</div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'salt/js/formatJSON.js' %}"></script>
<script>
    //选择环境显示文件列表
    $('#env').click(function(){
        var env=$(this).val() ;
        $('#file').html("");
        $.getJSON("{% url 'salt:config_fun' salt_server.id %}", {env: env}, function (result) {
             for (var i = result.length - 1; i >= 0; i--) {
                 $("<option value='"+result[i]+"'>"+result[i]+"</option>").appendTo("#file");
             }
        });
        return false;
    });
    //显示文件内容
    $('#file').click(function(){
        var file=$(this).val() ;
        var env=$('#env').val() ;
        $.getJSON("{% url 'salt:config_fun' salt_server.id %}", {env: env,file:file}, function (result) {
            var rv=document.getElementById('content');
            for (var k in result){
                rv.value=result[k];
                $('#name').html(k);
            }
        });
        return false;
    });
    //保存文件内容
    $('#write').click(function(){
        var env=$('#env').val() ;
        var file=$('#file').val();
        var content=$('#content').val() ;
        $.getJSON("{% url 'salt:config_fun' salt_server.id %}", {env:env,file:file,content:content}, function (result) {
            alert(result);
        });

        return false;
    });
</script>
{% endblock %}

templates/SALT/deploy.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% block title %}
    <title>代码发布</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            代码发布
            <small class="text-danger">{{ salt_server.idc.name }} -- {{ salt_server.url }} -- {{ salt_server.role }}</small>
            <div class="btn-group pull-right">
                <a class="btn btn-info" href="/admin/SALT/svnproject/add/" target="_blank" title="新建"><span class="glyphicon glyphicon-plus"></span></a>
{#            Server选择#}
                <div class="btn-group pull-right dropdown">
                    <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        &nbsp;SaltServer&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for s in server_list %}
                            <li><a href="{% url 'salt:deploy' s.id%}">{{ s.idc.name }} -- {{ s.url }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}


        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>项目名称</th>
                                <th>项目主机</th>
                                <th>本地地址</th>
                                <th>SVN账号</th>
                                <th>创建日期</th>
                                <th>相关信息</th>
                                <th>状态</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        {% for project in project_list %}
                            <tbody>
                                <tr>
                                    <td>{{ project.name }}</td>
                                    <td>{{ project.host }}</td>
                                    <td><a href="{{ project.url }}" target="_blank" title="{{ project.url }}">{{ project.path }}/{{ project.target }}</a></td>
                                    <td>{{ project.username }}</td>
                                    <td>{{ project.create_date }}</td>
                                    <td>{{ project.info|linebreaks }}</td>
                                    <td>{% if project.status == "新建" %}<a href="{% url 'salt:deploy' salt_server.id %}?project_id={{ project.id }}">{{ project.status }}</a>{% else %}{{ project.status }}{% endif %}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a class="btn btn-info btn-xs" href="/admin/SALT/svnproject/{{ project.id }}/" target="_blank">
                                                <span class="glyphicon glyphicon-edit">&nbsp;修改</span></a>
                                            <button class="btn btn-info btn-xs" type="button" onclick="svn('commit','{{ project.id }}')" >
                                                <span class="glyphicon glyphicon-send">&nbsp;提交</span></button>
                                            <button class="btn btn-info btn-xs" type="button" onclick="svn('update','{{ project.id }}')" >
                                                <span class="glyphicon glyphicon-refresh">&nbsp;更新</span></button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    <script>
        function svn(active,project_id){
            $.getJSON("{% url 'salt:deploy_fun' salt_server.id %}", {active:active,project_id:project_id}, function (result) {
                alert(result['msg']);
                if(result['add']){
                    window.open("/admin/SALT/svnproject/add/");
                }
            });
        }
    </script>
{% endblock %}

templates/SALT/minions.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% load pagination_tags %}
{% block title %}
    <title>Minions管理</title>
    <style>
        textarea {
            white-space: pre;
            font-family: Courier, monospace;
            width:100%;
            height:450px;
            background-color: black;
            color: #ffffff;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Minions管理
            <small class="text-danger">{{ salt_server.idc.name }} -- {{ salt_server.url }} -- {{ salt_server.role }}</small>
{#            Server选择#}
            <div class="btn-group pull-right dropdown">
                <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    &nbsp;SaltServer&nbsp;<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    {% for s in server_list %}
                        <li><a href="{% url 'salt:minions' s.id%}">{{ s.idc.name }} -- {{ s.url }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 text-center">
                {% if minion_list %}
                {% autopaginate minion_list 15 %}
                {% endif %}
                <div class="table-responsive" >
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Minion</th>
                                <th class="text-center">IP地址</th>
                                <th class="text-center">系统</th>
                                <th class="text-center">状态</th>
                                <th class="text-center">Grains</th>
                                <th class="text-center">Pillar</th>
                                <th class="text-center">操作</th>
                            </tr>
                        </thead>
                        {% for minion in minion_list %}
                            <tbody>
                                <tr>
                                    <td>{{ minion.minion }}</td>
                                    <td>{% for ip in minion.ip %}{{ ip }}&nbsp;{% endfor %}</td>
                                    <td>{{ minion.os }}</td>
                                    <td class="{% if minion.status == 'Accepted' %}bg-success{% elif minion.status == 'Unaccepted' %}bg-danger{% elif minion.status == 'Unknown' %} bg-alert {% else %}bg-info{% endif %}">{{ minion.status }}</td>
                                    <td><a href="#" onclick="active('{{ minion.id }}','grains','{{ minion.minion }}')" data-toggle="modal" data-target="#result">
                                        Grains</a></td>
                                    <td><a href="#" onclick="active('{{ minion.id }}','pillar','{{ minion.minion }}')" data-toggle="modal" data-target="#result">
                                        Pillar</a></td>
                                    <td>
                                        {% if minion.status == 'Accepted' %}
                                            <button class="btn btn-danger btn-xs" onclick="active('{{ minion.id }}','delete','{{ minion.minion }}')" title="删除KEY">
                                                <span class="glyphicon glyphicon-remove"></span></button>
                                        {% elif minion.status == 'Unaccepted' %}
                                            <a class="btn btn-success btn-xs" onclick="active('{{ minion.id }}','accept','{{ minion.minion }}')" title="接受KEY">
                                                <span class="glyphicon glyphicon-ok"></span></a>
                                        {% endif %}
                                    </td>
                                </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
                {% paginate %}
            </div>
        </div>
    </div>

<div class="modal fade" id="result" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4><code id="minion"></code>的<code id="target"></code>详细信息
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </h4>
            </div>
            <div class="modal-body">
                <label for="result_data" class="sr-only"></label>
                <textarea id="result_data"></textarea>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'salt/js/formatJSON.js' %}"></script>
    <script>
    function active(id,active,minion){
        $('#minion').html(minion);
        $('#target').html(active);
        if (active == 'grains' || active == 'pillar')
        {
            $.getJSON("{% url 'salt:minions_fun' %}",{id:id,active:active},function(result) {
                var rv = document.getElementById('result_data');
                rv.value = formatJson(result, true);
            });
        }
        else if(active == 'delete'){
            if(confirm("是否删除KEY'"+minion+"'?")){
                $.getJSON("{% url 'salt:minions_fun' %}",{id:id,active:active},function(result){
                    alert(result)
                })
            }
        }
    }
    </script>
{% endblock %}

templates/SALT/server.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% block title %}
    <title>Salt接口</title>
{#    <style>.panel {  margin-bottom: 0;  }.alert { margin-bottom: 0; }</style>#}
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            Salt接口列表
            <small class="text-danger">注意：同一机房必须且只能设置一个Master角色。</small>
            <span class="btn-group pull-right">
                <a class="btn btn-info " href="/admin/SALT/saltserver/add/" target="_blank">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp;接口</a>
            </span>
        </h2>
        <div class="table-responsive" >
            <table class="table table-hover table-bordered table-striped">
                <thead>
                    <tr>
                        <th>所属机房</th>
                        <th>URL地址</th>
                        <th>角色</th>
                        <th>账户名</th>
                        <th>操作</th>
                    </tr>
                </thead>
                {% for server in server_list %}
                <tbody>
                    <tr>
                        <td>{{ server.idc.name }}</td>
                        <td>{{ server.url }}</td>
                        <td>{{ server.get_role_display }}</td>
                        <td>{{ server.username }}</td>
                        <td>
                            <a class="btn btn-info btn-xs" href="/admin/SALT/saltserver/{{ server.id }}/" target="_blank">
                                <span class="glyphicon glyphicon-edit"></span>&nbsp;修&nbsp;改
                            </a>
                            <a class="btn btn-info btn-xs" href="{% url 'salt:config' server.id %} " >
                                <span class="glyphicon glyphicon-cog"></span>&nbsp;配&nbsp;置
                            </a>
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/SALT/state.html
{% extends "AUTH/navbar.html" %}
{% load staticfiles %}
{% load pagination_tags %}
{% block title %}
    <title>应用部署</title>
    <style>
        textarea {
            white-space: pre;
            font-family: Courier, monospace;
            width:100%;
            height:540px;
            background-color: black;
            color: #ffffff;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <h2>
            应用部署
            <small class="text-danger">{{ salt_server.idc.name }} -- {{ salt_server.url }} -- {{ salt_server.role }}</small>
{#            Server选择#}
            <div class="btn-group pull-right">
                <a href="{% url 'salt:config' salt_server.id %}" class="btn btn-info" title="配置文件" target="_blank">Config</a>
                <div class="btn-group pull-right dropdown">
                    <a href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        &nbsp;SaltServer&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for s in server_list %}
                            <li><a href="{% url 'salt:file_remote' s.id%}">{{ s.idc.name }} -- {{ s.url }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </h2>
        {% if error %}<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ error }}</div>{% endif %}
        {% if success %}<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert">&times;</a>{{ success }}</div>{% endif %}
        <div class="row">
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="form-group">
                    <label for="tgt">目标主机：</label>
                    <select class="form-control" multiple="multiple" size="4" id="tgt">
                        {% for minion in minion_list %}
                        <option value="{{ minion.minion }}">{{ minion.minion }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="env">环境列表：</label>
                    <select class="form-control" id="env">
                        <option >－－选择环境－－</option>
                        {% for env in envs %}
                        <option value="{{ env }}">{{ env }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="state">State模块：</label>
                    <div id="state"></div>
                </div>

                <button type="button" id="deploy" class="btn btn-info btn-lg btn-block">Deploy</button>
            </div>
            <div class="col-sm-9 col-md-9 col-lg-9">
                 <label for="result">部署结果：</label>
                <textarea id="result" rows="{{ result|length|add:'1' }}" style="min-height:300px;" readonly="readonly">[root@salt-master ~]#</textarea>

            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'salt/js/formatJSON.js' %}"></script>
    <script>
        //选择环境显示State
        $('#env').change(function(){
            var env=$(this).val() ;
            $('#state').html('');
            $.getJSON("{% url 'salt:state_fun' salt_server.id %}", {env: env}, function (result) {
                if (typeof result != 'object') { alert(result);}
                else {
                    for (var i = result.length - 1; i >= 0; i--) {
                        var item = '<div class="checkbox">' +
                                '<label><input type="checkbox" name="state" value="' + result[i] + '">' + result[i] + '</label>' +
                                '</div>';
                        $(item).appendTo("#state");
                    }
                }
            });
            return false;
        });
        $('#deploy').click(function(){
            var tgt = $('#tgt').val();
            var env = $('#env').val();
            var state="";
            var rv=document.getElementById('result');
            $("input:checkbox[name='state']:checked").each(function() {
                state += $(this).val() + ",";
            });
            if (!state){alert("请选择State模块！");}
            else if(!tgt){alert("请选择目标主机！");}
            else{
                $.getJSON("{% url 'salt:state_fun' salt_server.id %}", {tgt:tgt.toString(),env:env,state:state}, function (result) {
                    rv.value="[root@salt-master ~]# salt "+tgt+" state.sls "+state.substring(0,state.length-1)+" saltenv="+env;
                    for (var k in result) {
                        var v = result[k];
                        if (typeof v != 'object') {
                            rv.value += "\n" + k + ":" + v;
                        }
                        else {
                            rv.value += "\n" + k + ":" + formatJson(v, true);
                        }
                    }
                });
            }
        });
    </script>
{% endblock %}